insert into vacunas (id_vacuna, vacuna, dosis) values ('001', 'BCG', 'N/A');
insert into vacunas (id_vacuna, vacuna, dosis) values ('002', 'HEP.B', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('003', 'HEP.B', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('004', 'HEP.B', '3ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('005', 'VCN 13', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('006', 'VCN 13', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('007', 'VCN 13', '3ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('008', 'VCN 13', 'PREMA');
insert into vacunas (id_vacuna, vacuna, dosis) values ('010', 'VCN 13', '>65');
insert into vacunas (id_vacuna, vacuna, dosis) values ('011', 'VCN 13', 'P.S');
insert into vacunas (id_vacuna, vacuna, dosis) values ('012', 'VCN 13', '<65 FR');
insert into vacunas (id_vacuna, vacuna, dosis) values ('013', 'PENTAVALENTE', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('014', 'PENTAVALENTE', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('015', 'PENTAVALENTE', '3ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('016', 'SALK-IPV', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('017', 'SALK-IPV', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('018', 'SALK-IPV', '3ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('019', 'SALK-IPV', 'R');
insert into vacunas (id_vacuna, vacuna, dosis) values ('020', 'ROTAVIRUS', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('021', 'ROTAVIRUS', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('022', 'MENINGOCOCO', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('023', 'MENINGOCOCO', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('024', 'MENINGOCOCO', '3ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('025', 'MENINGOCOCO', 'R');
insert into vacunas (id_vacuna, vacuna, dosis) values ('026', 'ANTIGRIPAL', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('027', 'ANTIGRIPAL', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('028', 'ANTIGRIPAL', 'UD');
insert into vacunas (id_vacuna, vacuna, dosis) values ('029', 'ANTIGRIPAL', 'EMB');
insert into vacunas (id_vacuna, vacuna, dosis) values ('030', 'ANTIGRIPAL', 'P.S');
insert into vacunas (id_vacuna, vacuna, dosis) values ('031', 'ANTIGRIPAL', '>65');
insert into vacunas (id_vacuna, vacuna, dosis) values ('032', 'ANTIGRIPAL', '<65');
insert into vacunas (id_vacuna, vacuna, dosis) values ('033', 'ANTIGRIPAL', 'P.E');
insert into vacunas (id_vacuna, vacuna, dosis) values ('034', 'TRIPLE VIRAL', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('035', 'TRIPLE VIRAL', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('036', 'HEP.A', 'N/A');
insert into vacunas (id_vacuna, vacuna, dosis) values ('037', 'VARICELA', 'N/A');
insert into vacunas (id_vacuna, vacuna, dosis) values ('038', 'DTP Hib', 'N/A');
insert into vacunas (id_vacuna, vacuna, dosis) values ('039', 'DTP', 'N/A');
insert into vacunas (id_vacuna, vacuna, dosis) values ('040', 'DTP Ac.', 'N/A');
insert into vacunas (id_vacuna, vacuna, dosis) values ('041', 'DTP Ac.', 'EMB');
insert into vacunas (id_vacuna, vacuna, dosis) values ('042', 'DTP Ac.', '11A');
insert into vacunas (id_vacuna, vacuna, dosis) values ('043', 'DTP Ac.', 'P.S');
insert into vacunas (id_vacuna, vacuna, dosis) values ('044', 'HPV', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('045', 'HPV', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('046', 'DT', '1ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('047', 'DT', '2da');
insert into vacunas (id_vacuna, vacuna, dosis) values ('048', 'DT', '3ra');
insert into vacunas (id_vacuna, vacuna, dosis) values ('049', 'S.R', 'N/A');
insert into vacunas (id_vacuna, vacuna, dosis) values ('050', 'N23', 'N/A');

insert into marcas (id_marca, marca) values ('001', 'VIRAFLU');
insert into marcas (id_marca, marca) values ('002', 'FLUXVIR');
insert into marcas (id_marca, marca) values ('003', 'VIRAFLU PEDIATRICA');

